repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        # E402 module level import not at top of file
        # W503 line break before binary operator
        args: ["--max-line-length=105", "-j8", "--ignore=E402,W503"]
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args: [
          "--generated-members=cv2.*,player.*,alsaaudio.Mixer",
          "--disable=too-many-instance-attributes,line-too-long,eval-used,too-few-public-methods,broad-exception-caught,unused-argument,import-error,consider-using-with",
        ]
