# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '20 20 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 25
        days-before-close: 5
        remove-stale-when-updated: false
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        stale-issue-message: >
          No activity on this issue recently. Make sure you update to the latest
          version of LNXlink to check if the issue has been resolved.

          If no further activity occurs, the issue will be closed.
        stale-pr-message: >
          No activity on this Pull Request recently.
          If no further activity occurs, this PR will be closed.

          Thank you for your contributions.
